import {
  Call,
  Appointment,
  Lead,
  Notification,
  AnalyticsSummary,
  ChartDataPoint,
  Business,
} from "@/types";

// ─── Business ───────────────────────────────────────────────────────────────
export const mockBusiness: Business = {
  id: "biz_001",
  name: "Accra Dental Clinic",
  slug: "accra-dental",
  phone: "+233 24 123 4567",
  email: "info@accradental.com",
  industry: "Healthcare",
  timezone: "Africa/Accra",
  plan: "professional",
  greeting:
    "Hello! Thank you for calling Accra Dental Clinic. I'm your AI receptionist. How can I help you today?",
  forwardingNumber: "+233 24 987 6543",
  businessHours: {
    monday: { isOpen: true, open: "08:00", close: "18:00" },
    tuesday: { isOpen: true, open: "08:00", close: "18:00" },
    wednesday: { isOpen: true, open: "08:00", close: "18:00" },
    thursday: { isOpen: true, open: "08:00", close: "18:00" },
    friday: { isOpen: true, open: "08:00", close: "17:00" },
    saturday: { isOpen: true, open: "09:00", close: "13:00" },
    sunday: { isOpen: false, open: "09:00", close: "13:00" },
  },
  createdAt: "2024-11-01T09:00:00Z",
};

// ─── Analytics Summary ───────────────────────────────────────────────────────
export const mockAnalyticsSummary: AnalyticsSummary = {
  totalCalls: 1284,
  answeredCalls: 1261,
  missedCallsPrevented: 247,
  appointmentsBooked: 389,
  leadsCaptured: 156,
  aiSuccessRate: 94.2,
  avgCallDuration: 187,
  customerSatisfaction: 4.7,
  spamBlocked: 83,
};

// ─── Calls ───────────────────────────────────────────────────────────────────
export const mockCalls: Call[] = [
  {
    id: "call_001",
    businessId: "biz_001",
    callerName: "Kwame Asante",
    phone: "+233241234567",
    duration: 212,
    outcome: "appointment_booked",
    sentiment: "positive",
    appointmentBooked: true,
    leadCaptured: false,
    spamBlocked: false,
    summary:
      "Customer called to book a teeth cleaning appointment. AI confirmed availability for next Tuesday at 10 AM and booked successfully.",
    tags: ["dental", "cleaning", "new-patient"],
    transcript: [
      { id: "t1", role: "ai", content: "Hello! Thank you for calling Accra Dental Clinic. How can I help you today?", timestamp: 0 },
      { id: "t2", role: "customer", content: "Hi, I'd like to book an appointment for teeth cleaning.", timestamp: 8 },
      { id: "t3", role: "ai", content: "Of course! I'd be happy to help you schedule that. Could I get your name please?", timestamp: 12 },
      { id: "t4", role: "customer", content: "Sure, it's Kwame Asante.", timestamp: 18 },
      { id: "t5", role: "ai", content: "Thank you, Kwame. We have availability this Tuesday the 21st at 10 AM or Thursday at 2 PM. Which works better for you?", timestamp: 22 },
      { id: "t6", role: "customer", content: "Tuesday at 10 works perfectly.", timestamp: 34 },
      { id: "t7", role: "ai", content: "Excellent! I've booked your teeth cleaning appointment for Tuesday, May 21st at 10:00 AM. You'll receive a confirmation text shortly. Is there anything else I can help with?", timestamp: 38 },
      { id: "t8", role: "customer", content: "No that's great, thank you!", timestamp: 52 },
    ],
    createdAt: "2025-05-19T08:14:00Z",
  },
  {
    id: "call_002",
    businessId: "biz_001",
    callerName: "Abena Mensah",
    phone: "+233209876543",
    duration: 156,
    outcome: "lead_captured",
    sentiment: "positive",
    appointmentBooked: false,
    leadCaptured: true,
    spamBlocked: false,
    summary:
      "Caller inquired about dental implant costs. AI captured contact details and qualified as a high-value lead for follow-up.",
    tags: ["implants", "high-value", "follow-up"],
    transcript: [
      { id: "t1", role: "ai", content: "Thank you for calling Accra Dental Clinic! How can I assist you today?", timestamp: 0 },
      { id: "t2", role: "customer", content: "I was wondering how much dental implants cost.", timestamp: 7 },
      { id: "t3", role: "ai", content: "Great question! Dental implant pricing depends on your specific situation. Our specialist would love to give you a personalized consultation. May I get your contact details?", timestamp: 12 },
    ],
    createdAt: "2025-05-19T09:32:00Z",
  },
  {
    id: "call_003",
    businessId: "biz_001",
    callerName: "Unknown Caller",
    phone: "+233201111111",
    duration: 12,
    outcome: "spam",
    sentiment: "neutral",
    appointmentBooked: false,
    leadCaptured: false,
    spamBlocked: true,
    summary: "Identified as robocall/spam. Call terminated after spam detection.",
    tags: ["spam", "robocall"],
    transcript: [],
    createdAt: "2025-05-19T10:01:00Z",
  },
  {
    id: "call_004",
    businessId: "biz_001",
    callerName: "Kofi Boateng",
    phone: "+233244556677",
    duration: 298,
    outcome: "appointment_booked",
    sentiment: "positive",
    appointmentBooked: true,
    leadCaptured: false,
    spamBlocked: false,
    summary: "Patient called about toothache. AI booked emergency appointment for same day.",
    tags: ["emergency", "toothache", "existing-patient"],
    transcript: [],
    createdAt: "2025-05-19T11:15:00Z",
  },
  {
    id: "call_005",
    businessId: "biz_001",
    callerName: "Ama Owusu",
    phone: "+233277889900",
    duration: 134,
    outcome: "information_provided",
    sentiment: "neutral",
    appointmentBooked: false,
    leadCaptured: false,
    spamBlocked: false,
    summary: "Caller asked about insurance acceptance and business hours. AI provided complete information.",
    tags: ["insurance", "hours", "info"],
    transcript: [],
    createdAt: "2025-05-19T12:48:00Z",
  },
  {
    id: "call_006",
    businessId: "biz_001",
    callerName: "Yaw Darko",
    phone: "+233233445566",
    duration: 89,
    outcome: "callback_requested",
    sentiment: "neutral",
    appointmentBooked: false,
    leadCaptured: true,
    spamBlocked: false,
    summary: "Patient wanted to speak with a dentist directly. AI scheduled a callback for 3 PM.",
    tags: ["callback", "consultation"],
    transcript: [],
    createdAt: "2025-05-19T13:20:00Z",
  },
  {
    id: "call_007",
    businessId: "biz_001",
    callerName: "Efua Asante",
    phone: "+233265432198",
    duration: 201,
    outcome: "appointment_booked",
    sentiment: "positive",
    appointmentBooked: true,
    leadCaptured: false,
    spamBlocked: false,
    summary: "Child patient's mother called for pediatric dental check-up. Appointment booked for Saturday.",
    tags: ["pediatric", "check-up", "weekend"],
    transcript: [],
    createdAt: "2025-05-18T15:10:00Z",
  },
  {
    id: "call_008",
    businessId: "biz_001",
    callerName: "Nana Osei",
    phone: "+233254321987",
    duration: 178,
    outcome: "appointment_booked",
    sentiment: "positive",
    appointmentBooked: true,
    leadCaptured: false,
    spamBlocked: false,
    summary: "Returning patient booked teeth whitening session.",
    tags: ["whitening", "returning-patient"],
    transcript: [],
    createdAt: "2025-05-18T14:02:00Z",
  },
];

// ─── Appointments ─────────────────────────────────────────────────────────────
export const mockAppointments: Appointment[] = [
  {
    id: "apt_001",
    businessId: "biz_001",
    callId: "call_001",
    customerName: "Kwame Asante",
    customerPhone: "+233241234567",
    customerEmail: "kwame@email.com",
    dateTime: "2025-05-21T10:00:00Z",
    duration: 60,
    status: "confirmed",
    service: "Teeth Cleaning",
    notes: "First visit — new patient",
    reminderSent: true,
    bookedByAI: true,
    createdAt: "2025-05-19T08:14:00Z",
  },
  {
    id: "apt_002",
    businessId: "biz_001",
    callId: "call_004",
    customerName: "Kofi Boateng",
    customerPhone: "+233244556677",
    dateTime: "2025-05-19T14:00:00Z",
    duration: 30,
    status: "confirmed",
    service: "Emergency Consultation",
    notes: "Toothache — upper right molar",
    reminderSent: true,
    bookedByAI: true,
    createdAt: "2025-05-19T11:15:00Z",
  },
  {
    id: "apt_003",
    businessId: "biz_001",
    callId: "call_007",
    customerName: "Efua Asante",
    customerPhone: "+233265432198",
    dateTime: "2025-05-24T09:00:00Z",
    duration: 45,
    status: "pending",
    service: "Pediatric Check-up",
    notes: "Child, age 8. Mother accompanying.",
    reminderSent: false,
    bookedByAI: true,
    createdAt: "2025-05-18T15:10:00Z",
  },
  {
    id: "apt_004",
    businessId: "biz_001",
    callId: "call_008",
    customerName: "Nana Osei",
    customerPhone: "+233254321987",
    dateTime: "2025-05-22T11:00:00Z",
    duration: 90,
    status: "confirmed",
    service: "Teeth Whitening",
    reminderSent: true,
    bookedByAI: true,
    createdAt: "2025-05-18T14:02:00Z",
  },
  {
    id: "apt_005",
    businessId: "biz_001",
    customerName: "Adjoa Mensah",
    customerPhone: "+233271234567",
    dateTime: "2025-05-20T15:30:00Z",
    duration: 60,
    status: "completed",
    service: "Root Canal",
    reminderSent: true,
    bookedByAI: false,
    createdAt: "2025-05-16T10:00:00Z",
  },
];

// ─── Leads ────────────────────────────────────────────────────────────────────
export const mockLeads: Lead[] = [
  {
    id: "lead_001",
    businessId: "biz_001",
    callId: "call_002",
    name: "Abena Mensah",
    phone: "+233209876543",
    email: "abena@gmail.com",
    stage: "qualified",
    score: 87,
    source: "call",
    service: "Dental Implants",
    notes: "High value lead. Interested in full implant procedure. Has budget.",
    tags: ["high-value", "implants"],
    createdAt: "2025-05-19T09:32:00Z",
    lastContactedAt: "2025-05-19T09:32:00Z",
  },
  {
    id: "lead_002",
    businessId: "biz_001",
    callId: "call_006",
    name: "Yaw Darko",
    phone: "+233233445566",
    stage: "contacted",
    score: 64,
    source: "call",
    service: "General Consultation",
    notes: "Wanted to speak with a dentist. Callback scheduled for 3 PM today.",
    tags: ["callback"],
    createdAt: "2025-05-19T13:20:00Z",
  },
  {
    id: "lead_003",
    businessId: "biz_001",
    name: "Kojo Ofori",
    phone: "+233248765432",
    email: "kojo.ofori@company.com",
    company: "Ofori & Sons Ltd.",
    stage: "proposal",
    score: 91,
    source: "referral",
    service: "Corporate Dental Plan",
    notes: "Company of 45 employees. Interested in corporate wellness dental plan.",
    tags: ["corporate", "high-value", "bulk"],
    createdAt: "2025-05-17T11:00:00Z",
    lastContactedAt: "2025-05-18T14:00:00Z",
  },
  {
    id: "lead_004",
    businessId: "biz_001",
    name: "Mawuli Agbor",
    phone: "+233263214567",
    stage: "new",
    score: 42,
    source: "call",
    service: "Braces / Orthodontics",
    notes: "First-time inquiry. Has a teenager needing braces.",
    tags: ["orthodontics", "teenager"],
    createdAt: "2025-05-19T07:45:00Z",
  },
  {
    id: "lead_005",
    businessId: "biz_001",
    name: "Akosua Frimpong",
    phone: "+233556677889",
    email: "akosua.f@hotmail.com",
    stage: "converted",
    score: 95,
    source: "call",
    service: "Teeth Whitening",
    tags: ["converted", "whitening"],
    createdAt: "2025-05-14T09:00:00Z",
    lastContactedAt: "2025-05-15T10:00:00Z",
  },
  {
    id: "lead_006",
    businessId: "biz_001",
    name: "Fiifi Arhin",
    phone: "+233244987654",
    stage: "lost",
    score: 31,
    source: "call",
    service: "Dental Implants",
    notes: "Price was too high. Went to a competitor.",
    tags: ["price-sensitive", "lost"],
    createdAt: "2025-05-12T14:00:00Z",
  },
];

// ─── Notifications ────────────────────────────────────────────────────────────
export const mockNotifications: Notification[] = [
  {
    id: "notif_001",
    type: "appointment",
    title: "New Appointment Booked",
    message: "AI booked Kwame Asante for Teeth Cleaning on May 21 at 10 AM",
    read: false,
    createdAt: "2025-05-19T08:14:00Z",
    link: "/appointments",
  },
  {
    id: "notif_002",
    type: "lead",
    title: "High-Value Lead Captured",
    message: "Abena Mensah inquired about dental implants — score: 87",
    read: false,
    createdAt: "2025-05-19T09:32:00Z",
    link: "/leads",
  },
  {
    id: "notif_003",
    type: "call",
    title: "Emergency Call Handled",
    message: "AI handled emergency toothache call — appointment booked same day",
    read: false,
    createdAt: "2025-05-19T11:15:00Z",
    link: "/calls",
  },
  {
    id: "notif_004",
    type: "alert",
    title: "Spam Blocked",
    message: "83 spam/robocalls blocked this month",
    read: true,
    createdAt: "2025-05-19T06:00:00Z",
  },
  {
    id: "notif_005",
    type: "system",
    title: "AI Performance Report Ready",
    message: "Your weekly performance report is available",
    read: true,
    createdAt: "2025-05-19T00:00:00Z",
    link: "/analytics",
  },
];

// ─── Charts ───────────────────────────────────────────────────────────────────
export const callVolumeData: ChartDataPoint[] = [
  { label: "Mon", value: 42, value2: 38 },
  { label: "Tue", value: 58, value2: 54 },
  { label: "Wed", value: 67, value2: 61 },
  { label: "Thu", value: 51, value2: 47 },
  { label: "Fri", value: 73, value2: 69 },
  { label: "Sat", value: 34, value2: 31 },
  { label: "Sun", value: 18, value2: 15 },
];

export const weeklyAppointmentsData: ChartDataPoint[] = [
  { label: "Mon", value: 12 },
  { label: "Tue", value: 19 },
  { label: "Wed", value: 24 },
  { label: "Thu", value: 17 },
  { label: "Fri", value: 28 },
  { label: "Sat", value: 9 },
  { label: "Sun", value: 0 },
];

export const peakHoursData: ChartDataPoint[] = [
  { label: "8am", value: 8 },
  { label: "9am", value: 24 },
  { label: "10am", value: 38 },
  { label: "11am", value: 31 },
  { label: "12pm", value: 19 },
  { label: "1pm", value: 14 },
  { label: "2pm", value: 27 },
  { label: "3pm", value: 33 },
  { label: "4pm", value: 29 },
  { label: "5pm", value: 21 },
  { label: "6pm", value: 11 },
];

export const sentimentTrendData: ChartDataPoint[] = [
  { label: "Week 1", value: 78, value2: 14, value3: 8 },
  { label: "Week 2", value: 82, value2: 12, value3: 6 },
  { label: "Week 3", value: 79, value2: 15, value3: 6 },
  { label: "Week 4", value: 88, value2: 9, value3: 3 },
];

export const conversionData: ChartDataPoint[] = [
  { label: "Jan", value: 28 },
  { label: "Feb", value: 34 },
  { label: "Mar", value: 31 },
  { label: "Apr", value: 42 },
  { label: "May", value: 38 },
];

export const topQuestionsData = [
  { question: "Book an appointment", count: 312 },
  { question: "What are your hours?", count: 198 },
  { question: "How much does it cost?", count: 165 },
  { question: "Do you accept insurance?", count: 134 },
  { question: "Cancel/reschedule appointment", count: 97 },
  { question: "Emergency dental care", count: 78 },
];

export const activityFeed = [
  { id: "a1", icon: "phone", label: "AI answered call from Kwame Asante", time: "2 min ago", type: "call" },
  { id: "a2", icon: "calendar", label: "Appointment booked for Kofi Boateng — Emergency", time: "8 min ago", type: "appointment" },
  { id: "a3", icon: "user", label: "New lead captured: Abena Mensah (Implants)", time: "37 min ago", type: "lead" },
  { id: "a4", icon: "shield", label: "Spam call blocked", time: "1 hr ago", type: "spam" },
  { id: "a5", icon: "phone", label: "AI answered call from Ama Owusu", time: "1.5 hr ago", type: "call" },
  { id: "a6", icon: "calendar", label: "Appointment confirmed: Nana Osei — Whitening", time: "2 hr ago", type: "appointment" },
  { id: "a7", icon: "star", label: "4.8★ satisfaction rating received", time: "3 hr ago", type: "rating" },
  { id: "a8", icon: "user", label: "Lead Yaw Darko moved to Contacted", time: "4 hr ago", type: "lead" },
];
